service: cartier

frameworkVersion: '>=1.0.0 <2.0.0'

custom:
  account: ${opt:account}
  region: ${opt:region}
  bucket: ${opt:bucket}
  timeout: ${opt:timeout}
  rate: ${opt:rate}
  debug: ${opt:debug}
  prune:
    automatic: true
    number: 3
provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  timeout: ${self:custom.timeout}
  memorySize: 512
  logRetentionInDays: 7
  environment:
    ACCOUNT: ${self:custom.account}
    BUCKET: ${self:custom.bucket}
    TIMEOUT: ${self:custom.timeout}
    RATE: ${self:custom.rate}
    DEBUG: ${self:custom.debug}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'lambda:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - arn:aws:s3:::scenicroutes-*
functions:
  scheduler:
    handler: build/scheduler.main
    events:
      - schedule:
          name: scheduler-event
          description: 'Event to fire the scheduler service'
          rate: rate(${self:custom.rate} minutes)

resources:
  - ${file(config/dynamodb-job.json)}
  - ${file(config/dynamodb-area.json)}

plugins:
  - serverless-prune-plugin

package:
  exclude:
    - src/**
    - config/**
    - coverage/**
    - docs/**
    - build/**/*.d.ts
    - build/**/*.test.js
    - build/scripts/**
